# Generated by Django 5.2 on 2025-05-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='imageurl',
            new_name='imageUrl',
        ),
    ]
