# Generated by Django 5.2 on 2025-05-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_bid_options_alter_bid_bid_alter_bid_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageUrl',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
