# Generated by Django 5.2 on 2025-05-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageUrl',
            field=models.URLField(blank=True, default='default_image.jpg', max_length=1000, null=True),
        ),
    ]
