# Generated by Django 5.2 on 2025-05-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_bid_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageUrl',
            field=models.URLField(default='/static/images/default_image.jpg', max_length=1000),
        ),
    ]
