# Generated by Django 5.2 on 2025-05-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_listing_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageUrl',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/static/images/default.jpg', max_length=1000),
        ),
    ]
